### ISSUE TITLE
LDAP authentication

### ISSUE THREAD

**Issue by dan2020802** [linkedin/oncall#298]
Thanks for providing this code! I'm currently trying to implement one of the Docker images available into a Kubernetes cluster, and I'm able to get to the point where the website loads.

However, after following the guides for the ldap configuration, I run into the error on the login page of 'invalid username or password'.

The only log that appears to change is var/log/uwsgi/error.log, which mentions the falcon-cors message noted in #204 .

Is there an example config.yaml containing a 'known good' ldap configuration for AD? The server I use currently accepts ldap (not ldaps) requests.

Thanks in advance for your help!

**Comment by dan2020802** [comment]
I was able to stop the falcon_cors message by changing the 

`cors = CORS(allow_origins_list=config.get('allow_origins_list', []))`

to

`cors = CORS(allow_origins_list=['*'])`

in `app.py` (for some reason, it wouldn't take this information from `config.yaml`

However, this didn't fix the login issue. I have tried LDAP settings that work with other applications, but it doesn't seem to translate.

What am I missing here?

**Comment by houqp** [comment]
What's your auth config? If you share your full oncall config here, it will make it easier for other people to provide guidance.

If you are using the provided sample ldap module, all ldap configs can be found in __init__ method: https://github.com/linkedin/oncall/blob/master/src/oncall/auth/modules/ldap_example.py

**Comment by dan2020802** [comment]
Thanks for your response! Here's my config section:

(server names and specific data removed)

```
    auth:
      module: 'oncall.auth.modules.ldap_import'
      module: 'oncall.auth.modules.ldap_example'
      ldap_url: 'ldap://ad.server.org:389/'
      ldap_bind_user: 'domain\binduser'
      ldap_bind_password: 'bindpassword'
      ldap_base_dn: 'ou=Employees,dc=server,dc=org'
      ldap_search_filter: '(&(objectClass=person)(sAMAccountName=%s))'
      import_user: True
      attrs:
        username: 'person'
        full_name: 'cn'
        email: 'mail'
        call: 'telephone'
        sms: '0123456789'
        slack: 'user'
```
